// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1wSK8OYIYG2JIzblgo2Hi2aiUQMz7Rzc',
    appId: '1:384567628506:web:73e27e60951f5e7c7c4be3',
    messagingSenderId: '384567628506',
    projectId: 'app-movileslll',
    authDomain: 'app-movileslll.firebaseapp.com',
    databaseURL: 'https://app-movileslll-default-rtdb.firebaseio.com',
    storageBucket: 'app-movileslll.firebasestorage.app',
    measurementId: 'G-1EWY4N3CMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEk45uZau6N8VqxdA5qaatUUFil21rLRY',
    appId: '1:384567628506:android:774910cbeab685997c4be3',
    messagingSenderId: '384567628506',
    projectId: 'app-movileslll',
    databaseURL: 'https://app-movileslll-default-rtdb.firebaseio.com',
    storageBucket: 'app-movileslll.firebasestorage.app',
  );
}
